# Generated by Django 2.0 on 2018-01-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_pages', '0004_auto_20160628_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=256, null=True),
        ),
    ]
