# Generated by Django 2.0 on 2018-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_pages', '0005_auto_20180109_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIFrameURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, unique=True)),
                ('url', models.TextField(max_length=1024)),
            ],
        ),
    ]
