# Generated by Django 2.0 on 2018-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_pages', '0006_allowediframeurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowediframeurl',
            options={'ordering': ['url_name'], 'verbose_name': 'Allowed IFrame URL', 'verbose_name_plural': 'Allowed IFrame URLs'},
        ),
        migrations.AlterField(
            model_name='allowediframeurl',
            name='url_name',
            field=models.SlugField(help_text='Wordt gebruikt om de link naar de iframe-pagina te maken. Alleen letters, cijfers, liggende streepjes en verbindingsstreepjes toegestaan.', max_length=100, unique=True),
        ),
    ]
